#!/bin/bash

# ============================================================
# Kinect Device Setup Script
# ============================================================
# This script sets up USB permissions for Kinect devices
# (Xbox 360 Kinect, Kinect v2, ASUS Xtion) on Linux systems
#
# Usage: sudo ./device_setup.sh [username]
#
# If no username is provided, it will use the user who invoked sudo
# ============================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Kinect Device Permission Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}ERROR: This script must be run as root${NC}"
    echo "Please run: sudo $0"
    exit 1
fi

# Determine target user
if [ -n "$1" ]; then
    TARGET_USER="$1"
elif [ -n "$SUDO_USER" ]; then
    TARGET_USER="$SUDO_USER"
else
    echo -e "${RED}ERROR: Cannot determine target user${NC}"
    echo "Please run as: sudo $0 <username>"
    exit 1
fi

echo -e "${GREEN}Target user: ${TARGET_USER}${NC}"
echo ""

# Verify user exists
if ! id "$TARGET_USER" &>/dev/null; then
    echo -e "${RED}ERROR: User '${TARGET_USER}' does not exist${NC}"
    exit 1
fi

# Step 1: Add user to necessary groups
echo -e "${YELLOW}[1/7]${NC} Adding user '${TARGET_USER}' to necessary groups..."

for group in plugdev video dialout; do
    if getent group "$group" > /dev/null 2>&1; then
        usermod -aG "$group" "$TARGET_USER"
        echo -e "  ${GREEN}✓${NC} Added to group: $group"
    else
        echo -e "  ${YELLOW}⚠${NC} Group '$group' does not exist, creating it..."
        groupadd "$group"
        usermod -aG "$group" "$TARGET_USER"
        echo -e "  ${GREEN}✓${NC} Created and added to group: $group"
    fi
done

echo ""

# Step 2: Install udev rules
echo -e "${YELLOW}[2/7]${NC} Installing udev rules..."

RULES_FILE="/etc/udev/rules.d/99-kinect-devices.rules"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_RULES="${SCRIPT_DIR}/99-kinect-devices.rules"

if [ -f "$SOURCE_RULES" ]; then
    cp "$SOURCE_RULES" "$RULES_FILE"
    chmod 644 "$RULES_FILE"
    echo -e "  ${GREEN}✓${NC} Installed udev rules from: $SOURCE_RULES"
else
    echo -e "  ${YELLOW}⚠${NC} Source rules file not found, creating rules inline..."
    cat > "$RULES_FILE" << 'UDEV_RULES'
# udev rules for Kinect devices (Xbox 360 Kinect, Kinect v2/One, ASUS Xtion)
# Generated by device_setup.sh

# ============================================================
# Microsoft Kinect for Xbox 360 (Kinect v1)
# ============================================================
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02ae", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02b0", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02ad", MODE="0666", GROUP="plugdev"

# ============================================================
# Microsoft Kinect for Xbox One (Kinect v2)
# ============================================================
# Kinect v2 Main Camera/Depth Sensor
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02c4", MODE="0666", GROUP="plugdev"
# Kinect v2 Hub
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02c3", MODE="0666", GROUP="plugdev"
# Kinect v2 Additional interfaces
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02d8", MODE="0666", GROUP="plugdev"
# Kinect v2 Audio/NUI Sensor Adaptor
SUBSYSTEM=="usb", ATTR{idVendor}=="045e", ATTR{idProduct}=="02d9", MODE="0666", GROUP="plugdev"

# ============================================================
# ASUS Xtion PRO / PRO LIVE (PrimeSense-based devices)
# ============================================================
SUBSYSTEM=="usb", ATTR{idVendor}=="1d27", ATTR{idProduct}=="0600", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="1d27", ATTR{idProduct}=="0601", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="1d27", ATTR{idProduct}=="0609", MODE="0666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="1d27", MODE="0666", GROUP="plugdev"

# Make sure hidraw devices are accessible
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666", GROUP="plugdev"
UDEV_RULES
    chmod 644 "$RULES_FILE"
    echo -e "  ${GREEN}✓${NC} Created udev rules at: $RULES_FILE"
fi

echo ""

# Step 3: Reload udev rules
echo -e "${YELLOW}[3/7]${NC} Reloading udev rules..."
udevadm control --reload-rules
echo -e "  ${GREEN}✓${NC} udev rules reloaded"
echo ""

# Step 4: Trigger udev to apply rules
echo -e "${YELLOW}[4/7]${NC} Triggering udev to apply rules to connected devices..."
udevadm trigger --subsystem-match=usb --action=change
sleep 1
echo -e "  ${GREEN}✓${NC} udev triggered"
echo ""

# Step 5: Immediately fix permissions on connected Kinect devices
echo -e "${YELLOW}[5/7]${NC} Fixing permissions on currently connected Kinect devices..."

KINECT_FIXED=0

# Find all Kinect v2 devices and fix permissions immediately
for bus_dev in $(lsusb | grep -i "045e:02c4\|045e:02d8\|045e:02d9\|045e:02c3" | awk '{print $2 ":" $4}' | tr -d ':'); do
    bus=$(echo $bus_dev | cut -d: -f1)
    dev=$(echo $bus_dev | cut -d: -f2)
    dev_path="/dev/bus/usb/${bus}/${dev}"

    if [ -e "$dev_path" ]; then
        chmod 666 "$dev_path"
        echo -e "  ${GREEN}✓${NC} Fixed permissions: $dev_path (Kinect v2)"
        KINECT_FIXED=$((KINECT_FIXED + 1))
    fi
done

# Find all Kinect v1 devices
for bus_dev in $(lsusb | grep -i "045e:02ae\|045e:02b0\|045e:02ad" | awk '{print $2 ":" $4}' | tr -d ':'); do
    bus=$(echo $bus_dev | cut -d: -f1)
    dev=$(echo $bus_dev | cut -d: -f2)
    dev_path="/dev/bus/usb/${bus}/${dev}"

    if [ -e "$dev_path" ]; then
        chmod 666 "$dev_path"
        echo -e "  ${GREEN}✓${NC} Fixed permissions: $dev_path (Kinect v1)"
        KINECT_FIXED=$((KINECT_FIXED + 1))
    fi
done

# Find all ASUS Xtion devices
for bus_dev in $(lsusb | grep -i "1d27:" | awk '{print $2 ":" $4}' | tr -d ':'); do
    bus=$(echo $bus_dev | cut -d: -f1)
    dev=$(echo $bus_dev | cut -d: -f2)
    dev_path="/dev/bus/usb/${bus}/${dev}"

    if [ -e "$dev_path" ]; then
        chmod 666 "$dev_path"
        echo -e "  ${GREEN}✓${NC} Fixed permissions: $dev_path (ASUS Xtion)"
        KINECT_FIXED=$((KINECT_FIXED + 1))
    fi
done

if [ $KINECT_FIXED -eq 0 ]; then
    echo -e "  ${YELLOW}⚠${NC} No Kinect/Xtion devices found to fix"
else
    echo -e "  ${GREEN}✓${NC} Fixed permissions on $KINECT_FIXED device(s)"
fi

echo ""

# Step 6: Increase USB buffer size for Kinect v2
echo -e "${YELLOW}[6/7]${NC} Configuring USB buffer size for Kinect v2..."

CURRENT_BUFFER=$(cat /sys/module/usbcore/parameters/usbfs_memory_mb 2>/dev/null || echo "unknown")
echo -e "  Current USB buffer size: ${CYAN}${CURRENT_BUFFER} MB${NC}"

if [ "$CURRENT_BUFFER" != "unknown" ] && [ "$CURRENT_BUFFER" -lt 128 ]; then
    echo 128 > /sys/module/usbcore/parameters/usbfs_memory_mb
    NEW_BUFFER=$(cat /sys/module/usbcore/parameters/usbfs_memory_mb)
    echo -e "  ${GREEN}✓${NC} Increased USB buffer to: ${CYAN}${NEW_BUFFER} MB${NC}"

    # Make it persistent
    echo -e "  Making USB buffer setting persistent..."

    # Method 1: rc.local (if exists)
    if [ -f /etc/rc.local ]; then
        if ! grep -q "usbfs_memory_mb" /etc/rc.local; then
            sed -i '/^exit 0/i echo 128 > /sys/module/usbcore/parameters/usbfs_memory_mb' /etc/rc.local 2>/dev/null || true
        fi
    fi

    # Method 2: Create systemd service
    cat > /etc/systemd/system/kinect-usb-buffer.service << 'SYSTEMD_SERVICE'
[Unit]
Description=Set USB buffer size for Kinect v2
After=systemd-modules-load.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo 128 > /sys/module/usbcore/parameters/usbfs_memory_mb'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
SYSTEMD_SERVICE

    systemctl daemon-reload
    systemctl enable kinect-usb-buffer.service 2>/dev/null || true
    echo -e "  ${GREEN}✓${NC} Created systemd service for persistent USB buffer"
else
    echo -e "  ${GREEN}✓${NC} USB buffer already at ${CURRENT_BUFFER} MB (sufficient)"
fi

echo ""

# Step 7: Scan for connected devices and verify
echo -e "${YELLOW}[7/7]${NC} Verifying setup..."
echo ""

FOUND_DEVICES=0

echo -e "  ${CYAN}Connected Kinect Devices:${NC}"

# Check for Kinect v2
KINECT_V2=$(lsusb | grep -i "045e:02c4" || true)
if [ -n "$KINECT_V2" ]; then
    echo -e "  ${GREEN}✓${NC} Kinect v2 Camera detected"
    # Show permissions
    for bus_dev in $(echo "$KINECT_V2" | awk '{print $2 ":" $4}' | tr -d ':'); do
        bus=$(echo $bus_dev | cut -d: -f1)
        dev=$(echo $bus_dev | cut -d: -f2)
        dev_path="/dev/bus/usb/${bus}/${dev}"
        perms=$(ls -la "$dev_path" 2>/dev/null | awk '{print $1}')
        serial=$(lsusb -v -s ${bus}:${dev} 2>/dev/null | grep iSerial | awk '{print $3}' | head -1)
        echo -e "      Device: $dev_path | Permissions: ${CYAN}$perms${NC} | Serial: ${CYAN}$serial${NC}"
    done
    FOUND_DEVICES=1
fi

# Check for Kinect v2 Audio/Hub
KINECT_V2_AUX=$(lsusb | grep -i "045e:02d9" || true)
if [ -n "$KINECT_V2_AUX" ]; then
    echo -e "  ${GREEN}✓${NC} Kinect v2 NUI Sensor Adaptor detected"
    FOUND_DEVICES=1
fi

# Check for Kinect 360
KINECT_V1=$(lsusb | grep -i "045e:02ae\|045e:02b0\|045e:02ad" || true)
if [ -n "$KINECT_V1" ]; then
    echo -e "  ${GREEN}✓${NC} Kinect for Xbox 360 (v1) detected"
    FOUND_DEVICES=1
fi

# Check for ASUS Xtion
XTION=$(lsusb | grep -i "1d27:" || true)
if [ -n "$XTION" ]; then
    echo -e "  ${GREEN}✓${NC} ASUS Xtion / PrimeSense device detected"
    FOUND_DEVICES=1
fi

if [ $FOUND_DEVICES -eq 0 ]; then
    echo -e "  ${YELLOW}⚠${NC} No Kinect/Xtion devices currently connected"
fi

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✓ Setup completed successfully!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}IMPORTANT NOTES:${NC}"
echo ""
echo -e "1. ${CYAN}Group changes:${NC} Log out and log back in for group changes to take effect."
echo -e "   Or run: ${BLUE}newgrp plugdev${NC} in your current terminal"
echo ""
echo -e "2. ${CYAN}Docker users:${NC} Restart your Docker container to pick up the new permissions."
echo -e "   Make sure to run with: ${BLUE}--device=/dev/bus/usb${NC} or ${BLUE}--privileged${NC}"
echo ""
echo -e "3. ${CYAN}If devices are replugged:${NC} Run this script again or use:"
echo -e "   ${BLUE}sudo udevadm trigger --subsystem-match=usb --action=change${NC}"
echo ""
echo -e "4. ${CYAN}Verify your setup:${NC}"
echo -e "   ${BLUE}ls -la /dev/bus/usb/*/  | grep -E '00[6-9]|01[0-9]'${NC}"
echo -e "   Permissions should show: ${GREEN}crw-rw-rw-${NC} (666)"
echo ""
echo -e "5. ${CYAN}Test device detection:${NC}"
echo -e "   ${BLUE}lsusb | grep -E '045e|1d27'${NC}"
echo ""
